fixedUpdateRate: 60
maxSubSteps: 8
maxFrameDelta: 0.25
gravity:
- 0
- -9.81
- 0
allowSleeping: true
interpolationEnabled: true
collisionLayers:
  default:
    index: 0
    collidesWith:
    - default
    - world
    - player
    - box
  world:
    index: 1
    collidesWith:
    - box
    - default
    - player
  player:
    index: 2
    collidesWith:
    - default
    - player
    - world
  box:
    index: 3
    collidesWith:
    - default
    - world
solverIterations: 6
solverRelaxationIterations: 2
