<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackageId>Sandbox</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Editor\Vecxy.Editor.csproj" />
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Engine\Vecxy.Engine.csproj" />
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Input\Vecxy.Input.csproj" />
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Physics\Vecxy.Physics.csproj" />
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Scene\Vecxy.Scene.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Assets\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>
</Project>
