<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Game</AssemblyName>
    <RootNamespace>Game</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Engine\Vecxy.Engine.csproj" />
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Scene\Vecxy.Scene.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Assets\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>
</Project>
