<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VecxyGenerateEntryPoint>true</VecxyGenerateEntryPoint>
    <VecxyApplicationId>game.vecxy.tictactoe</VecxyApplicationId>
    <VecxyApplicationTitle>TicTacToe</VecxyApplicationTitle>
    <VecxyApplicationVersion>1.0.0</VecxyApplicationVersion>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <Import Project=".vecxy/Engine.props" />
</Project>
