capacity: 100
stacks:
  - itemId: spirit-blade
    quantity: 3
  - itemId: flame-blade
    quantity: 1
  - itemId: azure-dagger
    quantity: 6
  - itemId: blood-elixir
    quantity: 12
  - itemId: jade-elixir
    quantity: 5
  - itemId: spirit-ring
    quantity: 2
