referenceResolution:
  - 720
  - 1280
scaleMode: fit
scrollSpeed: 110
dragScrollThreshold: 8
scrollDeceleration: 2800
enableShadows: false
spriteAtlases:
  items: Assets/Textures/ItemsIconsAtlas.atlas
