<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VecxyApplicationId>game.vecxy.hardcorecultivation</VecxyApplicationId>
    <VecxyApplicationTitle>HardCore Cultivation</VecxyApplicationTitle>
    <VecxyApplicationVersion>1.0.0</VecxyApplicationVersion>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.45</AssemblyVersion>
    <FileVersion>1.0.0.45</FileVersion>
  </PropertyGroup>

  <Import Project="..\Engine\Vecxy\Code\Vecxy.Platforms\build\Vecxy.Platforms.props" />

  <ItemGroup>
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Engine\Vecxy.Engine.csproj" />
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Rendering\Vecxy.Rendering.csproj" />
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Scene\Vecxy.Scene.csproj" />
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Assets\Vecxy.Assets.csproj" />
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Kernel\Vecxy.Kernel.csproj" />
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Diagnostics\Vecxy.Diagnostics.csproj" />
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Physics\Vecxy.Physics.csproj" />
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.UI\Vecxy.UI.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(VecxyPlatform)' == 'Desktop'">
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Editor\Vecxy.Editor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Progression/GameProgress.cs" />
  </ItemGroup>
</Project>
