<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VecxyApplicationId>game.vecxy.hardcorecultivation</VecxyApplicationId>
    <VecxyApplicationTitle>HardCore Cultivation</VecxyApplicationTitle>
    <VecxyApplicationVersion>0.1.0</VecxyApplicationVersion>
  </PropertyGroup>

  <Import Project="..\Engine\Vecxy\Code\Vecxy.Platforms\build\Vecxy.Platforms.props" />

  <ItemGroup Condition="'$(VecxyPlatform)' == 'Desktop'">
    <ProjectReference Include="..\Engine\Vecxy\Code\Vecxy.Editor\Vecxy.Editor.csproj" />
  </ItemGroup>
</Project>
